name: SpaceBattle

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./SpaceBattle/SpaceBattle.Lib.Tests

      - name: Build
        run: dotnet build ./SpaceBattle/SpaceBattle.Lib.Tests

      - name: SpaceBattle-Unit-Test
        run: dotnet test /home/runner/work/OOAIP/OOAIP/SpaceBattle/SpaceBattle.Lib.Tests/SpaceBattle.Lib.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura



      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Generate Coverage Report
        run: |
          reportgenerator -reports:SpaceBattle/SpaceBattle.Lib.Tests/TestResults/coverage.cobertura.xml -targetdir:SpaceBattle/SpaceBattle.Lib.Tests/TestResults/CoverageReport -reporttypes:Html

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: CoverageReport
          path: SpaceBattle/SpaceBattle.Lib.Tests/TestResults/CoverageReport

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: SpaceBattle/SpaceBattle.Lib.Tests/TestResults 