name: SpaceBattle

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./SpaceBattle/SpaceBattle.Lib

      - name: Build
        run: cd SpaceBattle/SpaceBattle.Lib && dotnet build --no-restore && cd ../..

      - name: SpaceBattle-Unit-Test
        run: |
          cd SpaceBattle/SpaceBattle.Lib.Tests
          dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./TestResults/coverage.cobertura.xml
          cd ../..

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Generate Coverage Report
        run: |
          reportgenerator -reports:SpaceBattle/SpaceBattle.Lib.Tests/TestResults/coverage.cobertura.xml -targetdir:SpaceBattle/SpaceBattle.Lib.Tests/TestResults/CoverageReport -reporttypes:Html

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: CoverageReport
          path: SpaceBattle/SpaceBattle.Lib.Tests/TestResults/CoverageReport

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: SpaceBattle/SpaceBattle.Lib.Tests/TestResults
          