name: SpaceBattle

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['main']
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./SpaceBattle/SpaceBattle.Lib

      - name: Build
        run: cd SpaceBattle/SpaceBattle.Lib && dotnet build --no-restore && cd ../..

      - name: SpaceBattle-Unit-Test
        run: cd SpaceBattle/SpaceBattle.Lib.Tests && dotnet test --collect:"XPlat Code Coverage"
        
      - name: Checkstyle
        run: cd SpaceBattle/SpaceBattle.Lib.Tests && dotnet format --verify-no-changes

      - name: CodeCov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
